### ISSUE TITLE
部分情况下无法resize和双击全屏

### ISSUE THREAD

**Issue by hcaihao** [winsoft666/Qt-FramelessWindow#3]
窗口全屏后，鼠标移动到最上方边缘会变成可resize状态，这个时候向下调整窗口大小，然后拖动标题栏，会还原原始尺寸，此时就无法resize和双击全屏了

![动画](https://user-images.githubusercontent.com/3926845/128964260-59e0927e-83e7-4243-b9dc-35c8c04f4840.gif)

**Comment by winsoft666** [comment]
Fixed!
