### ISSUE TITLE
你好，发现一个BUG 窗口最大化后拖动位置

### ISSUE THREAD

**Issue by reghtml** [winsoft666/Qt-FramelessWindow#5]
窗口最大化后拖动标题栏移动软件位置触发BUG

之后再双击标题栏无法最大化或恢复， 鼠标拖拽边框也无法调整大小

**Comment by winsoft666** [comment]
Could you reproduce this problem 100%?
I just use `QtFramelessWindowSample` tested, it's ok

**Comment by reghtml** [comment]
我使用您的demo测试的 ，

其中的原因，是因为一般软件最大化后，不能拖拽标题栏，一拖拽软件会恢复默认大小，然后跟随鼠标移动，

但是这个demo最大化后还是可以拖拽标题栏移动位置。 并没有恢复到默认大小，而且 此时双击标题栏不会恢复默认大小，也无法拖拉边框改变大小 ， 需要多次双击标题栏才可以 ， 

没事小问题， 最大化后还去拖拽标题栏 也算不是常用操作

**Comment by reghtml** [comment]
我尝试修改代码，在移动鼠标的时间函数中先判断是否最大化状态，如果是最大化就恢复默认状态

可以解决这个问题，但是唯一的遗憾是窗体的位置不是太友好，他不是像一般软件一样，在最大化状态下拖拽标题栏， 标题栏跟随在鼠标的位置

这个好像要按缩小之后的界面尺寸 按照鼠标在最大化时候的位置比例 去计算，这个不知道改哪里了

**Comment by reghtml** [comment]
![图片](https://user-images.githubusercontent.com/15364651/159484996-7b483e3c-041e-48a7-856c-fa0ddece4a57.png)

**Comment by winsoft666** [comment]
> 我使用您的demo测试的 ，
> 
> 其中的原因，是因为一般软件最大化后，不能拖拽标题栏，一拖拽软件会恢复默认大小，然后跟随鼠标移动，
> 
> 但是这个demo最大化后还是可以拖拽标题栏移动位置。 并没有恢复到默认大小，而且 此时双击标题栏不会恢复默认大小，也无法拖拉边框改变大小 ， 需要多次双击标题栏才可以 ，
> 
> 没事小问题， 最大化后还去拖拽标题栏 也算不是常用操作

What's your os version?
I test on windows10, it' ok.
